dist: trusty
language: java
jdk:
  - oraclejdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn install
  - rm -rf $HOME/.m2/repository/am.zgh.snakegame

install: true

script:
- ./build.sh
